"""Add actions column to policies

Revision ID: 2131c0619e1b
Revises: 87f9565846cb
Create Date: 2025-10-31 14:57:58.375471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2131c0619e1b'
down_revision: Union[str, Sequence[str], None] = '87f9565846cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('actions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'actions')
    # ### end Alembic commands ###
