"""Create work_anniversary_greetings table

Revision ID: 6276e7aa279d
Revises: 
Create Date: 2025-10-30 16:32:37.010683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6276e7aa279d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_name', sa.String(), nullable=True),
    sa.Column('attendance_condition', sa.String(), nullable=True),
    sa.Column('days_more_than', sa.Integer(), nullable=True),
    sa.Column('send_letter', sa.String(), nullable=True),
    sa.Column('check_every', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_name'), 'alerts', ['alert_name'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('birthday_greetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('send_copy', sa.Boolean(), nullable=True),
    sa.Column('post_feed', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birthday_greetings_id'), 'birthday_greetings', ['id'], unique=False)
    op.create_table('letter_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_name', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letter_history_id'), 'letter_history', ['id'], unique=False)
    op.create_table('letter_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_offer_letter', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letter_templates_id'), 'letter_templates', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('employee_search', sa.String(length=255), nullable=True),
    sa.Column('send_option', sa.Enum('SEND_NOW', 'SEND_LATER', name='sendoption'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_department'), 'notifications', ['department'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_location'), 'notifications', ['location'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('UPLOADED', 'ONLINE', name='policytype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_policy_name'), 'policies', ['policy_name'], unique=False)
    op.create_table('wedding_anniversary_greetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('send_copy', sa.Boolean(), nullable=True),
    sa.Column('post_feed', sa.Boolean(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wedding_anniversary_greetings_id'), 'wedding_anniversary_greetings', ['id'], unique=False)
    op.create_table('work_anniversary_greetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('send_copy', sa.Boolean(), nullable=True),
    sa.Column('post_feed', sa.Boolean(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_anniversary_greetings_id'), 'work_anniversary_greetings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_anniversary_greetings_id'), table_name='work_anniversary_greetings')
    op.drop_table('work_anniversary_greetings')
    op.drop_index(op.f('ix_wedding_anniversary_greetings_id'), table_name='wedding_anniversary_greetings')
    op.drop_table('wedding_anniversary_greetings')
    op.drop_index(op.f('ix_policies_policy_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_notifications_location'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_department'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_letter_templates_id'), table_name='letter_templates')
    op.drop_table('letter_templates')
    op.drop_index(op.f('ix_letter_history_id'), table_name='letter_history')
    op.drop_table('letter_history')
    op.drop_index(op.f('ix_birthday_greetings_id'), table_name='birthday_greetings')
    op.drop_table('birthday_greetings')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_name'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
