"""Add search_employee column to birthday_greetings

Revision ID: 87f9565846cb
Revises: 6276e7aa279d
Create Date: 2025-10-31 11:32:37.361956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f9565846cb'
down_revision: Union[str, Sequence[str], None] = '6276e7aa279d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birthday_greetings', sa.Column('search_employee', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birthday_greetings', 'search_employee')
    # ### end Alembic commands ###
